const fs = require('fs')
const DB_PATH = '/home/jai/apps/db.json'

const classes = [
  {
    id: 'barbarian',
    name: 'Bárbaro',
    nameEn: 'Barbarian',
    hitDie: 12,
    primaryAbility: 'FUE',
    savingThrows: ['FUE', 'CON'],
    armorProficiencies: ['Ligera', 'Media', 'Escudos'],
    weaponProficiencies: ['Armas simples', 'Armas marciales'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Atletismo', 'Intimidación', 'Naturaleza', 'Percepción', 'Supervivencia', 'Trato con animales'],
    startingEquipment: 'Hacha grande o cualquier arma marcial cuerpo a cuerpo; 2 hachas de mano o cualquier arma simple; pack de explorador y 4 jabalinas',
    spellcaster: false,
    spellcastingAbility: null,
    subclassLevel: 3,
    subclassName: 'Senda Primordial',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, rages: 2,           rageDamage: 2, features: ['Rabia', 'Defensa sin Armadura', 'Arma de Bárbaro'] },
      2:  { profBonus: 2, rages: 2,           rageDamage: 2, features: ['Ataque Descuidado', 'Sentido del Peligro', 'Movimiento de Bárbaro'] },
      3:  { profBonus: 2, rages: 3,           rageDamage: 2, features: ['Senda Primordial', 'Instinto Primario'] },
      4:  { profBonus: 2, rages: 3,           rageDamage: 2, features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, rages: 3,           rageDamage: 2, features: ['Ataque Extra', 'Movimiento Rápido'] },
      6:  { profBonus: 3, rages: 4,           rageDamage: 2, features: ['Característica de Senda Primordial'] },
      7:  { profBonus: 3, rages: 4,           rageDamage: 2, features: ['Instinto Salvaje', 'Conocimiento Instintivo'] },
      8:  { profBonus: 3, rages: 4,           rageDamage: 2, features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, rages: 4,           rageDamage: 3, features: ['Golpe Brutal (1 dado)'] },
      10: { profBonus: 4, rages: 4,           rageDamage: 3, features: ['Característica de Senda Primordial'] },
      11: { profBonus: 4, rages: 4,           rageDamage: 3, features: ['Rabia Implacable'] },
      12: { profBonus: 4, rages: 5,           rageDamage: 3, features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, rages: 5,           rageDamage: 3, features: ['Golpe Brutal (2 dados)'] },
      14: { profBonus: 5, rages: 5,           rageDamage: 3, features: ['Característica de Senda Primordial'] },
      15: { profBonus: 5, rages: 5,           rageDamage: 3, features: ['Rabia Persistente'] },
      16: { profBonus: 5, rages: 5,           rageDamage: 4, features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, rages: 6,           rageDamage: 4, features: ['Golpe Brutal (3 dados)'] },
      18: { profBonus: 6, rages: 6,           rageDamage: 4, features: ['Poder Indomable'] },
      19: { profBonus: 6, rages: 6,           rageDamage: 4, features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, rages: 'Sin límite', rageDamage: 4, features: ['Campeón Primordial'] }
    }
  },
  {
    id: 'bard',
    name: 'Bardo',
    nameEn: 'Bard',
    hitDie: 8,
    primaryAbility: 'CAR',
    savingThrows: ['DES', 'CAR'],
    armorProficiencies: ['Ligera'],
    weaponProficiencies: ['Armas simples', 'Ballesta de mano', 'Espada larga', 'Estoque', 'Espada corta'],
    toolProficiencies: ['3 instrumentos musicales a elección'],
    skillChoices: 3,
    skillOptions: ['todas'],
    startingEquipment: 'Estoque o espada larga o cualquier arma simple; Ballesta de mano y 20 virotes o cualquier arma simple; pack de diplomático o pack de artista; Armadura de cuero, daga, instrumento musical',
    spellcaster: true,
    spellcastingAbility: 'CAR',
    subclassLevel: 3,
    subclassName: 'Colegio de Bardo',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, cantrips: 2, spellsKnown: 4,  slots: [2],                 features: ['Lanzamiento de Conjuros', 'Inspiración de Bardo (d6)'] },
      2:  { profBonus: 2, cantrips: 2, spellsKnown: 5,  slots: [3,0],               features: ['Canción de Descanso (d6)', 'Competencia Versátil'] },
      3:  { profBonus: 2, cantrips: 2, spellsKnown: 6,  slots: [4,2],               features: ['Colegio de Bardo', 'Experiencia'] },
      4:  { profBonus: 2, cantrips: 3, spellsKnown: 7,  slots: [4,3],               features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, cantrips: 3, spellsKnown: 8,  slots: [4,3,2],             features: ['Inspiración de Bardo (d8)', 'Fuente de Inspiración', 'Canción de Descanso (d8)'] },
      6:  { profBonus: 3, cantrips: 3, spellsKnown: 9,  slots: [4,3,3],             features: ['Característica de Colegio de Bardo', 'Contraencantamiento'] },
      7:  { profBonus: 3, cantrips: 3, spellsKnown: 10, slots: [4,3,3,1],           features: [] },
      8:  { profBonus: 3, cantrips: 3, spellsKnown: 11, slots: [4,3,3,2],           features: ['Mejora de Puntuación de Característica', 'Canción de Descanso (d10)'] },
      9:  { profBonus: 4, cantrips: 3, spellsKnown: 12, slots: [4,3,3,3,1],         features: ['Secretos Mágicos'] },
      10: { profBonus: 4, cantrips: 4, spellsKnown: 14, slots: [4,3,3,3,2],         features: ['Inspiración de Bardo (d10)', 'Experiencia Mejorada', 'Secretos Mágicos'] },
      11: { profBonus: 4, cantrips: 4, spellsKnown: 15, slots: [4,3,3,3,2,1],       features: [] },
      12: { profBonus: 4, cantrips: 4, spellsKnown: 15, slots: [4,3,3,3,2,1],       features: ['Mejora de Puntuación de Característica', 'Canción de Descanso (d12)'] },
      13: { profBonus: 5, cantrips: 4, spellsKnown: 16, slots: [4,3,3,3,2,1,1],     features: [] },
      14: { profBonus: 5, cantrips: 4, spellsKnown: 18, slots: [4,3,3,3,2,1,1],     features: ['Característica de Colegio de Bardo', 'Secretos Mágicos'] },
      15: { profBonus: 5, cantrips: 4, spellsKnown: 19, slots: [4,3,3,3,2,1,1,1],   features: ['Inspiración de Bardo (d12)'] },
      16: { profBonus: 5, cantrips: 4, spellsKnown: 19, slots: [4,3,3,3,2,1,1,1],   features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, cantrips: 4, spellsKnown: 20, slots: [4,3,3,3,2,1,1,1,1], features: [] },
      18: { profBonus: 6, cantrips: 4, spellsKnown: 22, slots: [4,3,3,3,3,1,1,1,1], features: ['Secretos Mágicos', 'Canción de Descanso Inigualable'] },
      19: { profBonus: 6, cantrips: 4, spellsKnown: 22, slots: [4,3,3,3,3,2,1,1,1], features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, cantrips: 4, spellsKnown: 22, slots: [4,3,3,3,3,2,2,1,1], features: ['Inspiración de Bardo Superior'] }
    }
  },
  {
    id: 'cleric',
    name: 'Clérigo',
    nameEn: 'Cleric',
    hitDie: 8,
    primaryAbility: 'SAB',
    savingThrows: ['SAB', 'CAR'],
    armorProficiencies: ['Ligera', 'Media', 'Escudos'],
    weaponProficiencies: ['Armas simples'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Historia', 'Perspicacia', 'Medicina', 'Persuasión', 'Religión'],
    startingEquipment: 'Maza o símbolo sagrado; Escama o armadura de cuero; Ballesta ligera y 20 virotes o cualquier arma simple; Pack de sacerdote o pack de explorador; Escudo y símbolo sagrado',
    spellcaster: true,
    spellcastingAbility: 'SAB',
    subclassLevel: 1,
    subclassName: 'Dominio Divino',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, cantrips: 3, slots: [2],                 features: ['Lanzamiento de Conjuros', 'Dominio Divino', 'Conjuros de Dominio'] },
      2:  { profBonus: 2, cantrips: 3, slots: [3,0],               features: ['Canalizar Divinidad (x1)', 'Característica de Dominio Divino'] },
      3:  { profBonus: 2, cantrips: 3, slots: [4,2],               features: [] },
      4:  { profBonus: 2, cantrips: 4, slots: [4,3],               features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, cantrips: 4, slots: [4,3,2],             features: ['Destruir No-Muertos (CR 1/2)', 'Golpe Divino o Potencia de Conjuros'] },
      6:  { profBonus: 3, cantrips: 4, slots: [4,3,3],             features: ['Canalizar Divinidad (x2)', 'Característica de Dominio Divino'] },
      7:  { profBonus: 3, cantrips: 4, slots: [4,3,3,1],           features: [] },
      8:  { profBonus: 3, cantrips: 4, slots: [4,3,3,2],           features: ['Mejora de Puntuación de Característica', 'Destruir No-Muertos (CR 1)', 'Característica de Dominio Divino'] },
      9:  { profBonus: 4, cantrips: 4, slots: [4,3,3,3,1],         features: [] },
      10: { profBonus: 4, cantrips: 5, slots: [4,3,3,3,2],         features: ['Intervención Divina'] },
      11: { profBonus: 4, cantrips: 5, slots: [4,3,3,3,2,1],       features: ['Destruir No-Muertos (CR 2)'] },
      12: { profBonus: 4, cantrips: 5, slots: [4,3,3,3,2,1],       features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, cantrips: 5, slots: [4,3,3,3,2,1,1],     features: [] },
      14: { profBonus: 5, cantrips: 5, slots: [4,3,3,3,2,1,1],     features: ['Destruir No-Muertos (CR 3)'] },
      15: { profBonus: 5, cantrips: 5, slots: [4,3,3,3,2,1,1,1],   features: [] },
      16: { profBonus: 5, cantrips: 5, slots: [4,3,3,3,2,1,1,1],   features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, cantrips: 5, slots: [4,3,3,3,2,1,1,1,1], features: ['Destruir No-Muertos (CR 4)', 'Característica de Dominio Divino'] },
      18: { profBonus: 6, cantrips: 5, slots: [4,3,3,3,3,1,1,1,1], features: ['Canalizar Divinidad (x3)'] },
      19: { profBonus: 6, cantrips: 5, slots: [4,3,3,3,3,2,1,1,1], features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, cantrips: 5, slots: [4,3,3,3,3,2,2,1,1], features: ['Intervención Divina Mejorada'] }
    }
  },
  {
    id: 'druid',
    name: 'Druida',
    nameEn: 'Druid',
    hitDie: 8,
    primaryAbility: 'SAB',
    savingThrows: ['INT', 'SAB'],
    armorProficiencies: ['Ligera', 'Media', 'Escudos (no metálicos)'],
    weaponProficiencies: ['Garrotes', 'Dagas', 'Dardos', 'Jabalinas', 'Mazas', 'Bastones', 'Cimitarras', 'Hondas', 'Lanzas'],
    toolProficiencies: ['Herramientas de herborista'],
    skillChoices: 2,
    skillOptions: ['Arcanos', 'Trato con animales', 'Perspicacia', 'Medicina', 'Naturaleza', 'Percepción', 'Religión', 'Supervivencia'],
    startingEquipment: 'Escudo de madera o cualquier arma simple; Cimitarra o cualquier arma cuerpo a cuerpo simple; Armadura de cuero, pack de explorador, foco druídico',
    spellcaster: true,
    spellcastingAbility: 'SAB',
    subclassLevel: 2,
    subclassName: 'Círculo Druídico',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, cantrips: 2, slots: [2],                 features: ['Lanzamiento de Conjuros', 'Druídico', 'Conocimiento de la Naturaleza'] },
      2:  { profBonus: 2, cantrips: 2, slots: [3,0],               features: ['Forma Salvaje (CR 1/4)', 'Círculo Druídico'] },
      3:  { profBonus: 2, cantrips: 2, slots: [4,2],               features: [] },
      4:  { profBonus: 2, cantrips: 3, slots: [4,3],               features: ['Mejora de Puntuación de Característica', 'Forma Salvaje (CR 1/2)'] },
      5:  { profBonus: 3, cantrips: 3, slots: [4,3,2],             features: [] },
      6:  { profBonus: 3, cantrips: 3, slots: [4,3,3],             features: ['Característica de Círculo Druídico', 'Forma Salvaje (CR 1)'] },
      7:  { profBonus: 3, cantrips: 3, slots: [4,3,3,1],           features: [] },
      8:  { profBonus: 3, cantrips: 3, slots: [4,3,3,2],           features: ['Mejora de Puntuación de Característica', 'Forma Salvaje (CR 2)'] },
      9:  { profBonus: 4, cantrips: 3, slots: [4,3,3,3,1],         features: [] },
      10: { profBonus: 4, cantrips: 4, slots: [4,3,3,3,2],         features: ['Característica de Círculo Druídico', 'Forma Salvaje (CR 3)'] },
      11: { profBonus: 4, cantrips: 4, slots: [4,3,3,3,2,1],       features: [] },
      12: { profBonus: 4, cantrips: 4, slots: [4,3,3,3,2,1],       features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, cantrips: 4, slots: [4,3,3,3,2,1,1],     features: [] },
      14: { profBonus: 5, cantrips: 4, slots: [4,3,3,3,2,1,1],     features: ['Característica de Círculo Druídico', 'Forma Salvaje (CR 4)'] },
      15: { profBonus: 5, cantrips: 4, slots: [4,3,3,3,2,1,1,1],   features: [] },
      16: { profBonus: 5, cantrips: 4, slots: [4,3,3,3,2,1,1,1],   features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, cantrips: 4, slots: [4,3,3,3,2,1,1,1,1], features: [] },
      18: { profBonus: 6, cantrips: 4, slots: [4,3,3,3,3,1,1,1,1], features: ['Cuerpo Eterno', 'Hablar con las Plantas'] },
      19: { profBonus: 6, cantrips: 4, slots: [4,3,3,3,3,2,1,1,1], features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, cantrips: 4, slots: [4,3,3,3,3,2,2,1,1], features: ['Archidruida'] }
    }
  },
  {
    id: 'fighter',
    name: 'Guerrero',
    nameEn: 'Fighter',
    hitDie: 10,
    primaryAbility: 'FUE o DES',
    savingThrows: ['FUE', 'CON'],
    armorProficiencies: ['Todas', 'Escudos'],
    weaponProficiencies: ['Armas simples', 'Armas marciales'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Acrobacia', 'Trato con animales', 'Atletismo', 'Historia', 'Perspicacia', 'Intimidación', 'Percepción', 'Supervivencia'],
    startingEquipment: 'Cota de malla o armadura de cuero con arco largo y 20 flechas; Arma marcial y escudo o dos armas marciales; Ballesta ligera y 20 virotes o 2 hachas de mano; Pack de dungeonero o pack de explorador',
    spellcaster: false,
    spellcastingAbility: null,
    subclassLevel: 3,
    subclassName: 'Arquetipo Marcial',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, features: ['Estilo de Combate', 'Segundo Aire'] },
      2:  { profBonus: 2, features: ['Oleada de Acción (x1)'] },
      3:  { profBonus: 2, features: ['Arquetipo Marcial'] },
      4:  { profBonus: 2, features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, features: ['Ataque Extra (x2)'] },
      6:  { profBonus: 3, features: ['Mejora de Puntuación de Característica'] },
      7:  { profBonus: 3, features: ['Característica de Arquetipo Marcial'] },
      8:  { profBonus: 3, features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, features: ['Indomable (x1)'] },
      10: { profBonus: 4, features: ['Característica de Arquetipo Marcial'] },
      11: { profBonus: 4, features: ['Ataque Extra (x3)'] },
      12: { profBonus: 4, features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, features: ['Indomable (x2)'] },
      14: { profBonus: 5, features: ['Mejora de Puntuación de Característica'] },
      15: { profBonus: 5, features: ['Característica de Arquetipo Marcial'] },
      16: { profBonus: 5, features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, features: ['Oleada de Acción (x2)', 'Indomable (x3)'] },
      18: { profBonus: 6, features: ['Característica de Arquetipo Marcial'] },
      19: { profBonus: 6, features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, features: ['Ataque Extra (x4)'] }
    }
  },
  {
    id: 'monk',
    name: 'Monje',
    nameEn: 'Monk',
    hitDie: 8,
    primaryAbility: 'DES y SAB',
    savingThrows: ['FUE', 'DES'],
    armorProficiencies: [],
    weaponProficiencies: ['Armas simples', 'Espadas cortas'],
    toolProficiencies: ['1 tipo de herramienta artesana o 1 instrumento musical'],
    skillChoices: 2,
    skillOptions: ['Acrobacia', 'Atletismo', 'Historia', 'Perspicacia', 'Religión', 'Sigilo'],
    startingEquipment: 'Espada corta o cualquier arma simple; Pack de dungeonero o pack de explorador; 10 dardos',
    spellcaster: false,
    spellcastingAbility: null,
    subclassLevel: 3,
    subclassName: 'Tradición Monástica',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, kiPoints: 0,  martialDie: 4,  movement: 0,  features: ['Defensa sin Armadura', 'Artes Marciales (d4)'] },
      2:  { profBonus: 2, kiPoints: 2,  martialDie: 4,  movement: 10, features: ['Ki', 'Movimiento sin Armadura (+10)', 'Paso Neblinoso'] },
      3:  { profBonus: 2, kiPoints: 3,  martialDie: 4,  movement: 10, features: ['Tradición Monástica', 'Deflectar Proyectiles'] },
      4:  { profBonus: 2, kiPoints: 4,  martialDie: 4,  movement: 10, features: ['Mejora de Puntuación de Característica', 'Caída Lenta'] },
      5:  { profBonus: 3, kiPoints: 5,  martialDie: 6,  movement: 10, features: ['Ataque Extra', 'Golpe Aturdidor', 'Artes Marciales (d6)'] },
      6:  { profBonus: 3, kiPoints: 6,  martialDie: 6,  movement: 15, features: ['Golpes de Ki', 'Movimiento sin Armadura (+15)', 'Característica de Tradición Monástica'] },
      7:  { profBonus: 3, kiPoints: 7,  martialDie: 6,  movement: 15, features: ['Evasión', 'Quietud de Mente'] },
      8:  { profBonus: 3, kiPoints: 8,  martialDie: 6,  movement: 15, features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, kiPoints: 9,  martialDie: 6,  movement: 15, features: ['Silueta Ininterrumpida'] },
      10: { profBonus: 4, kiPoints: 10, martialDie: 6,  movement: 20, features: ['Pureza de Cuerpo', 'Movimiento sin Armadura (+20)'] },
      11: { profBonus: 4, kiPoints: 11, martialDie: 8,  movement: 20, features: ['Característica de Tradición Monástica', 'Artes Marciales (d8)'] },
      12: { profBonus: 4, kiPoints: 12, martialDie: 8,  movement: 20, features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, kiPoints: 13, martialDie: 8,  movement: 20, features: ['Lengua del Sol y la Luna'] },
      14: { profBonus: 5, kiPoints: 14, martialDie: 8,  movement: 25, features: ['Alma de Diamante', 'Movimiento sin Armadura (+25)'] },
      15: { profBonus: 5, kiPoints: 15, martialDie: 8,  movement: 25, features: ['Cuerpo Eterno del Monje'] },
      16: { profBonus: 5, kiPoints: 16, martialDie: 8,  movement: 25, features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, kiPoints: 17, martialDie: 10, movement: 25, features: ['Característica de Tradición Monástica', 'Artes Marciales (d10)'] },
      18: { profBonus: 6, kiPoints: 18, martialDie: 10, movement: 30, features: ['Ser Vacío', 'Movimiento sin Armadura (+30)'] },
      19: { profBonus: 6, kiPoints: 19, martialDie: 10, movement: 30, features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, kiPoints: 20, martialDie: 10, movement: 30, features: ['Alma Perfecta'] }
    }
  },
  {
    id: 'paladin',
    name: 'Paladín',
    nameEn: 'Paladin',
    hitDie: 10,
    primaryAbility: 'FUE y CAR',
    savingThrows: ['SAB', 'CAR'],
    armorProficiencies: ['Todas', 'Escudos'],
    weaponProficiencies: ['Armas simples', 'Armas marciales'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Atletismo', 'Perspicacia', 'Intimidación', 'Medicina', 'Persuasión', 'Religión'],
    startingEquipment: 'Arma marcial y escudo o dos armas marciales; 5 jabalinas o cualquier arma simple cuerpo a cuerpo; Pack de sacerdote o pack de explorador; Cota de malla y símbolo sagrado',
    spellcaster: true,
    spellcastingAbility: 'CAR',
    subclassLevel: 3,
    subclassName: 'Juramento Sagrado',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, slots: [],         features: ['Detección Divina', 'Imposición de Manos'] },
      2:  { profBonus: 2, slots: [2],        features: ['Estilo de Combate', 'Lanzamiento de Conjuros', 'Smite Divino'] },
      3:  { profBonus: 2, slots: [3,0],      features: ['Juramento Sagrado', 'Salud Divina', 'Conjuros de Juramento'] },
      4:  { profBonus: 2, slots: [3,0],      features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, slots: [4,2],      features: ['Ataque Extra'] },
      6:  { profBonus: 3, slots: [4,2],      features: ['Aura de Protección'] },
      7:  { profBonus: 3, slots: [4,3],      features: ['Característica de Juramento Sagrado'] },
      8:  { profBonus: 3, slots: [4,3],      features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, slots: [4,3,2],    features: [] },
      10: { profBonus: 4, slots: [4,3,2],    features: ['Aura de Coraje'] },
      11: { profBonus: 4, slots: [4,3,3],    features: ['Smite Divino Mejorado'] },
      12: { profBonus: 4, slots: [4,3,3],    features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, slots: [4,3,3,1],  features: [] },
      14: { profBonus: 5, slots: [4,3,3,1],  features: ['Toque Purificador'] },
      15: { profBonus: 5, slots: [4,3,3,2],  features: ['Característica de Juramento Sagrado'] },
      16: { profBonus: 5, slots: [4,3,3,2],  features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, slots: [4,3,3,3,1],features: [] },
      18: { profBonus: 6, slots: [4,3,3,3,1],features: ['Aura mejorada (30 pies)'] },
      19: { profBonus: 6, slots: [4,3,3,3,2],features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, slots: [4,3,3,3,2],features: ['Campeón Sagrado'] }
    }
  },
  {
    id: 'ranger',
    name: 'Explorador',
    nameEn: 'Ranger',
    hitDie: 10,
    primaryAbility: 'DES y SAB',
    savingThrows: ['FUE', 'DES'],
    armorProficiencies: ['Ligera', 'Media', 'Escudos'],
    weaponProficiencies: ['Armas simples', 'Armas marciales'],
    toolProficiencies: [],
    skillChoices: 3,
    skillOptions: ['Trato con animales', 'Atletismo', 'Perspicacia', 'Investigación', 'Naturaleza', 'Percepción', 'Sigilo', 'Supervivencia'],
    startingEquipment: 'Cota de escamas o armadura de cuero; Dos espadas cortas o dos armas simples cuerpo a cuerpo; Pack de dungeonero o pack de explorador; Arco largo y carcaj con 20 flechas',
    spellcaster: true,
    spellcastingAbility: 'SAB',
    subclassLevel: 3,
    subclassName: 'Arquetipo de Explorador',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, slots: [],         features: ['Favorito del Terreno', 'Enemigo Favorito', 'Arma de Explorador'] },
      2:  { profBonus: 2, slots: [2],        features: ['Estilo de Combate', 'Lanzamiento de Conjuros'] },
      3:  { profBonus: 2, slots: [3,0],      features: ['Arquetipo de Explorador', 'Conciencia Primitiva'] },
      4:  { profBonus: 2, slots: [3,0],      features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, slots: [4,2],      features: ['Ataque Extra'] },
      6:  { profBonus: 3, slots: [4,2],      features: ['Favorito del Terreno Mejorado', 'Movimiento de Explorador'] },
      7:  { profBonus: 3, slots: [4,3],      features: ['Característica de Arquetipo de Explorador'] },
      8:  { profBonus: 3, slots: [4,3],      features: ['Mejora de Puntuación de Característica', 'Paso por la Tierra'] },
      9:  { profBonus: 4, slots: [4,3,2],    features: [] },
      10: { profBonus: 4, slots: [4,3,2],    features: ['Enemigo Favorito Mejorado', 'Ocultarse a Plena Vista'] },
      11: { profBonus: 4, slots: [4,3,3],    features: ['Característica de Arquetipo de Explorador'] },
      12: { profBonus: 4, slots: [4,3,3],    features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, slots: [4,3,3,1],  features: [] },
      14: { profBonus: 5, slots: [4,3,3,1],  features: ['Desvanecerse'] },
      15: { profBonus: 5, slots: [4,3,3,2],  features: ['Característica de Arquetipo de Explorador'] },
      16: { profBonus: 5, slots: [4,3,3,2],  features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, slots: [4,3,3,3,1],features: [] },
      18: { profBonus: 6, slots: [4,3,3,3,1],features: ['Sentidos Salvajes', 'Esquivar Flechas'] },
      19: { profBonus: 6, slots: [4,3,3,3,2],features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, slots: [4,3,3,3,2],features: ['Asesino de Enemigos'] }
    }
  },
  {
    id: 'rogue',
    name: 'Pícaro',
    nameEn: 'Rogue',
    hitDie: 8,
    primaryAbility: 'DES',
    savingThrows: ['DES', 'INT'],
    armorProficiencies: ['Ligera'],
    weaponProficiencies: ['Armas simples', 'Ballesta de mano', 'Espada larga', 'Estoque', 'Espada corta'],
    toolProficiencies: ['Herramientas de ladrón'],
    skillChoices: 4,
    skillOptions: ['todas'],
    startingEquipment: 'Estoque o espada corta; Arco corto y carcaj con 20 flechas o espada corta; Pack de burlador o pack de dungeonero; Armadura de cuero, 2 dagas, herramientas de ladrón',
    spellcaster: false,
    spellcastingAbility: null,
    subclassLevel: 3,
    subclassName: 'Arquetipo de Pícaro',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, sneakAttack: '1d6',  features: ['Pericia', 'Ataque Furtivo (1d6)', 'Jerga de Ladrones'] },
      2:  { profBonus: 2, sneakAttack: '1d6',  features: ['Acción Astuta'] },
      3:  { profBonus: 2, sneakAttack: '2d6',  features: ['Arquetipo de Pícaro', 'Ataque Furtivo (2d6)'] },
      4:  { profBonus: 2, sneakAttack: '2d6',  features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, sneakAttack: '3d6',  features: ['Ataque Furtivo (3d6)', 'Esquiva Prodigiosa'] },
      6:  { profBonus: 3, sneakAttack: '3d6',  features: ['Pericia'] },
      7:  { profBonus: 3, sneakAttack: '4d6',  features: ['Evasión', 'Ataque Furtivo (4d6)'] },
      8:  { profBonus: 3, sneakAttack: '4d6',  features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, sneakAttack: '5d6',  features: ['Característica de Arquetipo de Pícaro', 'Ataque Furtivo (5d6)'] },
      10: { profBonus: 4, sneakAttack: '5d6',  features: ['Mejora de Puntuación de Característica'] },
      11: { profBonus: 4, sneakAttack: '6d6',  features: ['Talento Confiable', 'Ataque Furtivo (6d6)'] },
      12: { profBonus: 4, sneakAttack: '6d6',  features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, sneakAttack: '7d6',  features: ['Característica de Arquetipo de Pícaro', 'Ataque Furtivo (7d6)'] },
      14: { profBonus: 5, sneakAttack: '7d6',  features: ['Vista de Ladrón'] },
      15: { profBonus: 5, sneakAttack: '8d6',  features: ['Mente Escurridiza', 'Ataque Furtivo (8d6)'] },
      16: { profBonus: 5, sneakAttack: '8d6',  features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, sneakAttack: '9d6',  features: ['Característica de Arquetipo de Pícaro', 'Ataque Furtivo (9d6)'] },
      18: { profBonus: 6, sneakAttack: '9d6',  features: ['Escurridizo'] },
      19: { profBonus: 6, sneakAttack: '10d6', features: ['Mejora de Puntuación de Característica Épica', 'Ataque Furtivo (10d6)'] },
      20: { profBonus: 6, sneakAttack: '10d6', features: ['Golpe Afortunado'] }
    }
  },
  {
    id: 'sorcerer',
    name: 'Hechicero',
    nameEn: 'Sorcerer',
    hitDie: 6,
    primaryAbility: 'CAR',
    savingThrows: ['CON', 'CAR'],
    armorProficiencies: [],
    weaponProficiencies: ['Dagas', 'Dardos', 'Hondas', 'Bastones', 'Ballestas de mano'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Arcanos', 'Engaño', 'Perspicacia', 'Intimidación', 'Persuasión', 'Religión'],
    startingEquipment: 'Ballesta de mano y 20 virotes o cualquier arma simple; Bolsa de componentes o foco arcano; Pack de explorador o pack de diplomático; 2 dagas',
    spellcaster: true,
    spellcastingAbility: 'CAR',
    subclassLevel: 1,
    subclassName: 'Origen Mágico',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, cantrips: 4, spellsKnown: 2,  sorceryPoints: 0,  slots: [2],                 features: ['Lanzamiento de Conjuros', 'Origen Mágico'] },
      2:  { profBonus: 2, cantrips: 4, spellsKnown: 3,  sorceryPoints: 2,  slots: [3,0],               features: ['Puntos de Hechicería', 'Metamagia (x2)'] },
      3:  { profBonus: 2, cantrips: 4, spellsKnown: 4,  sorceryPoints: 3,  slots: [4,2],               features: [] },
      4:  { profBonus: 2, cantrips: 5, spellsKnown: 5,  sorceryPoints: 4,  slots: [4,3],               features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, cantrips: 5, spellsKnown: 6,  sorceryPoints: 5,  slots: [4,3,2],             features: [] },
      6:  { profBonus: 3, cantrips: 5, spellsKnown: 7,  sorceryPoints: 6,  slots: [4,3,3],             features: ['Característica de Origen Mágico'] },
      7:  { profBonus: 3, cantrips: 5, spellsKnown: 8,  sorceryPoints: 7,  slots: [4,3,3,1],           features: [] },
      8:  { profBonus: 3, cantrips: 5, spellsKnown: 9,  sorceryPoints: 8,  slots: [4,3,3,2],           features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, cantrips: 5, spellsKnown: 10, sorceryPoints: 9,  slots: [4,3,3,3,1],         features: [] },
      10: { profBonus: 4, cantrips: 6, spellsKnown: 11, sorceryPoints: 10, slots: [4,3,3,3,2],         features: ['Metamagia (x3)'] },
      11: { profBonus: 4, cantrips: 6, spellsKnown: 12, sorceryPoints: 11, slots: [4,3,3,3,2,1],       features: [] },
      12: { profBonus: 4, cantrips: 6, spellsKnown: 12, sorceryPoints: 12, slots: [4,3,3,3,2,1],       features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, cantrips: 6, spellsKnown: 13, sorceryPoints: 13, slots: [4,3,3,3,2,1,1],     features: [] },
      14: { profBonus: 5, cantrips: 6, spellsKnown: 13, sorceryPoints: 14, slots: [4,3,3,3,2,1,1],     features: ['Característica de Origen Mágico'] },
      15: { profBonus: 5, cantrips: 6, spellsKnown: 14, sorceryPoints: 15, slots: [4,3,3,3,2,1,1,1],   features: [] },
      16: { profBonus: 5, cantrips: 6, spellsKnown: 14, sorceryPoints: 16, slots: [4,3,3,3,2,1,1,1],   features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, cantrips: 6, spellsKnown: 15, sorceryPoints: 17, slots: [4,3,3,3,2,1,1,1,1], features: ['Metamagia (x4)'] },
      18: { profBonus: 6, cantrips: 6, spellsKnown: 15, sorceryPoints: 18, slots: [4,3,3,3,3,1,1,1,1], features: ['Característica de Origen Mágico'] },
      19: { profBonus: 6, cantrips: 6, spellsKnown: 15, sorceryPoints: 19, slots: [4,3,3,3,3,2,1,1,1], features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, cantrips: 6, spellsKnown: 15, sorceryPoints: 20, slots: [4,3,3,3,3,2,2,1,1], features: ['Restauración de Hechicería'] }
    }
  },
  {
    id: 'warlock',
    name: 'Brujo',
    nameEn: 'Warlock',
    hitDie: 8,
    primaryAbility: 'CAR',
    savingThrows: ['SAB', 'CAR'],
    armorProficiencies: ['Ligera'],
    weaponProficiencies: ['Armas simples'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Arcanos', 'Engaño', 'Historia', 'Intimidación', 'Investigación', 'Naturaleza', 'Religión'],
    startingEquipment: 'Ballesta ligera y 20 virotes o cualquier arma simple; Bolsa de componentes o foco arcano; Pack de estudioso o pack de dungeonero; Armadura de cuero, cualquier arma simple, 2 dagas',
    spellcaster: true,
    spellcastingAbility: 'CAR',
    spellcastingType: 'pacto',
    subclassLevel: 1,
    subclassName: 'Patrón Ultraterreno',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, cantrips: 2, spellsKnown: 2,  invocations: 0, pactSlots: 1, pactSlotLevel: 1, features: ['Patrón Ultraterreno', 'Magia de Pacto'] },
      2:  { profBonus: 2, cantrips: 2, spellsKnown: 3,  invocations: 2, pactSlots: 2, pactSlotLevel: 1, features: ['Invocaciones Sobrenaturales'] },
      3:  { profBonus: 2, cantrips: 2, spellsKnown: 4,  invocations: 2, pactSlots: 2, pactSlotLevel: 2, features: ['Bendición del Pacto'] },
      4:  { profBonus: 2, cantrips: 3, spellsKnown: 5,  invocations: 2, pactSlots: 2, pactSlotLevel: 2, features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, cantrips: 3, spellsKnown: 6,  invocations: 3, pactSlots: 2, pactSlotLevel: 3, features: [] },
      6:  { profBonus: 3, cantrips: 3, spellsKnown: 7,  invocations: 3, pactSlots: 2, pactSlotLevel: 3, features: ['Característica de Patrón Ultraterreno'] },
      7:  { profBonus: 3, cantrips: 3, spellsKnown: 8,  invocations: 4, pactSlots: 2, pactSlotLevel: 4, features: [] },
      8:  { profBonus: 3, cantrips: 3, spellsKnown: 9,  invocations: 4, pactSlots: 2, pactSlotLevel: 4, features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, cantrips: 3, spellsKnown: 10, invocations: 5, pactSlots: 2, pactSlotLevel: 5, features: [] },
      10: { profBonus: 4, cantrips: 4, spellsKnown: 10, invocations: 5, pactSlots: 2, pactSlotLevel: 5, features: ['Característica de Patrón Ultraterreno'] },
      11: { profBonus: 4, cantrips: 4, spellsKnown: 11, invocations: 5, pactSlots: 3, pactSlotLevel: 5, features: ['Arcano Místico (Nv.6)'] },
      12: { profBonus: 4, cantrips: 4, spellsKnown: 11, invocations: 6, pactSlots: 3, pactSlotLevel: 5, features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, cantrips: 4, spellsKnown: 12, invocations: 6, pactSlots: 3, pactSlotLevel: 5, features: ['Arcano Místico (Nv.7)'] },
      14: { profBonus: 5, cantrips: 4, spellsKnown: 12, invocations: 6, pactSlots: 3, pactSlotLevel: 5, features: ['Característica de Patrón Ultraterreno'] },
      15: { profBonus: 5, cantrips: 4, spellsKnown: 13, invocations: 7, pactSlots: 3, pactSlotLevel: 5, features: ['Arcano Místico (Nv.8)'] },
      16: { profBonus: 5, cantrips: 4, spellsKnown: 13, invocations: 7, pactSlots: 3, pactSlotLevel: 5, features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, cantrips: 4, spellsKnown: 14, invocations: 7, pactSlots: 4, pactSlotLevel: 5, features: ['Arcano Místico (Nv.9)'] },
      18: { profBonus: 6, cantrips: 4, spellsKnown: 14, invocations: 8, pactSlots: 4, pactSlotLevel: 5, features: [] },
      19: { profBonus: 6, cantrips: 4, spellsKnown: 15, invocations: 8, pactSlots: 4, pactSlotLevel: 5, features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, cantrips: 4, spellsKnown: 15, invocations: 8, pactSlots: 4, pactSlotLevel: 5, features: ['Maestro Etéreo'] }
    }
  },
  {
    id: 'wizard',
    name: 'Mago',
    nameEn: 'Wizard',
    hitDie: 6,
    primaryAbility: 'INT',
    savingThrows: ['INT', 'SAB'],
    armorProficiencies: [],
    weaponProficiencies: ['Dagas', 'Dardos', 'Hondas', 'Bastones', 'Ballestas de mano'],
    toolProficiencies: [],
    skillChoices: 2,
    skillOptions: ['Arcanos', 'Historia', 'Perspicacia', 'Investigación', 'Medicina', 'Religión'],
    startingEquipment: 'Bastón o daga; Bolsa de componentes o foco arcano; Pack de estudioso o pack de explorador; Libro de conjuros',
    spellcaster: true,
    spellcastingAbility: 'INT',
    subclassLevel: 2,
    subclassName: 'Tradición Arcana',
    source: 'SRD 5.2',
    levels: {
      1:  { profBonus: 2, cantrips: 3, spellsKnown: 6,  slots: [2],                 features: ['Lanzamiento de Conjuros', 'Recuperación Arcana'] },
      2:  { profBonus: 2, cantrips: 3, spellsKnown: 8,  slots: [3,0],               features: ['Tradición Arcana'] },
      3:  { profBonus: 2, cantrips: 3, spellsKnown: 10, slots: [4,2],               features: [] },
      4:  { profBonus: 2, cantrips: 4, spellsKnown: 12, slots: [4,3],               features: ['Mejora de Puntuación de Característica'] },
      5:  { profBonus: 3, cantrips: 4, spellsKnown: 14, slots: [4,3,2],             features: [] },
      6:  { profBonus: 3, cantrips: 4, spellsKnown: 16, slots: [4,3,3],             features: ['Característica de Tradición Arcana'] },
      7:  { profBonus: 3, cantrips: 4, spellsKnown: 18, slots: [4,3,3,1],           features: [] },
      8:  { profBonus: 3, cantrips: 4, spellsKnown: 20, slots: [4,3,3,2],           features: ['Mejora de Puntuación de Característica'] },
      9:  { profBonus: 4, cantrips: 4, spellsKnown: 22, slots: [4,3,3,3,1],         features: [] },
      10: { profBonus: 4, cantrips: 5, spellsKnown: 24, slots: [4,3,3,3,2],         features: ['Característica de Tradición Arcana'] },
      11: { profBonus: 4, cantrips: 5, spellsKnown: 26, slots: [4,3,3,3,2,1],       features: [] },
      12: { profBonus: 4, cantrips: 5, spellsKnown: 28, slots: [4,3,3,3,2,1],       features: ['Mejora de Puntuación de Característica'] },
      13: { profBonus: 5, cantrips: 5, spellsKnown: 30, slots: [4,3,3,3,2,1,1],     features: [] },
      14: { profBonus: 5, cantrips: 5, spellsKnown: 32, slots: [4,3,3,3,2,1,1],     features: ['Característica de Tradición Arcana'] },
      15: { profBonus: 5, cantrips: 5, spellsKnown: 34, slots: [4,3,3,3,2,1,1,1],   features: [] },
      16: { profBonus: 5, cantrips: 5, spellsKnown: 36, slots: [4,3,3,3,2,1,1,1],   features: ['Mejora de Puntuación de Característica'] },
      17: { profBonus: 6, cantrips: 5, spellsKnown: 38, slots: [4,3,3,3,2,1,1,1,1], features: [] },
      18: { profBonus: 6, cantrips: 5, spellsKnown: 40, slots: [4,3,3,3,3,1,1,1,1], features: ['Maestría en Conjuros'] },
      19: { profBonus: 6, cantrips: 5, spellsKnown: 42, slots: [4,3,3,3,3,2,1,1,1], features: ['Mejora de Puntuación de Característica Épica'] },
      20: { profBonus: 6, cantrips: 5, spellsKnown: 44, slots: [4,3,3,3,3,2,2,1,1], features: ['Maestría en Conjuros Firmada'] }
    }
  }
]

const db = JSON.parse(fs.readFileSync(DB_PATH, 'utf8'))
if (!db.dnd.refData) db.dnd.refData = {}
db.dnd.refData.classes = classes
fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2))
console.log(`✅ Insertadas ${classes.length} clases en db.json`)
console.log('Clases:', classes.map(c => c.name).join(', '))
